## Explainable k-Medoids

In [1]:
import matplotlib.pyplot as plt
from sklearn import datasets
import mpl_toolkits.mplot3d 
from sklearn.cluster import KMeans
from sklearn import metrics
import numpy as np
import pandas as pd

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [3]:
kmeans = KMeans(n_clusters=3, random_state=3).fit(X)

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
preds = kmeans.predict(X)
print(preds)
print(preds.shape)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]
(150,)


### !! darf ich nicht so machen, da sonst fehler bei cluster zuordnung!

#prediction is "false" but only because the "label" is not correct, the class itself is correctly predicted. Maybe this needs to be solved later on differently.

lst = []

for i in preds:
    if i == 1: 
        lst.append(0)
    elif i == 0:
        lst.append(1)
    else:
        lst.append(i)
        
preds = np.array(lst)

In [6]:
preds

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)

In [7]:
metrics.accuracy_score(y,preds)

0.24

In [8]:
centers = kmeans.cluster_centers_
print(centers)
print(centers.shape)

[[5.9016129  2.7483871  4.39354839 1.43387097]
 [5.006      3.428      1.462      0.246     ]
 [6.85       3.07368421 5.74210526 2.07105263]]
(3, 4)


In [9]:
# one set of clusters for every obs - Idk. how to broadcast this to work with the later distance function
centers_lst = []

for i in preds:
    centers_lst.append(np.array(centers))

In [10]:
c = np.array(centers_lst)

In [11]:
#Check obs
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [12]:
#check cluster
c[0]

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [13]:
#check point-wise Manhatten distance
abs(c[0] - X[0])

array([[0.8016129 , 0.7516129 , 2.99354839, 1.23387097],
       [0.094     , 0.072     , 0.062     , 0.046     ],
       [1.75      , 0.42631579, 4.34210526, 1.87105263]])

In [14]:
#check point-wise euclidean distance
(c[0] - X[0])**2

array([[6.42583247e-01, 5.64921956e-01, 8.96133195e+00, 1.52243757e+00],
       [8.83600000e-03, 5.18400000e-03, 3.84400000e-03, 2.11600000e-03],
       [3.06250000e+00, 1.81745152e-01, 1.88538781e+01, 3.50083795e+00]])

In [15]:
def calc_feature_wise_distance_matrix(distance_metric, points, cluster_centers):
    
    # calculate the distance of every feature value of ever obs to every feature value in every cluster.
    
    feature_wise_distance_matrix = []
    
    if distance_metric == "manhattan":
        for i,e in enumerate(X):
            feature_wise_distance_matrix.append(abs(c[i] - e))
        
    
    if distance_metric == "euclidean":
        for i,e in enumerate(X):
            feature_wise_distance_matrix.append((c[i] - e)**2)
    
    return np.array(feature_wise_distance_matrix)

In [16]:
A =calc_feature_wise_distance_matrix("manhattan", X, c)

In [17]:
A[0]

array([[0.8016129 , 0.7516129 , 2.99354839, 1.23387097],
       [0.094     , 0.072     , 0.062     , 0.046     ],
       [1.75      , 0.42631579, 4.34210526, 1.87105263]])

In [18]:
A[0][:,1]

array([0.7516129 , 0.072     , 0.42631579])

In [19]:
# Falsch!
def best_second_calc(feature_based_distanes, preds):
    
    num_features = feature_based_distanes.shape[1]
    
    assinged_cluster_list = []
    fb_distance_to_assinged_cluster_list = []
    
    best_alterantive_list = []
    fb_distance_to_best_alternative_list = []
    
    #for every obs:
    for idx, e in enumerate(feature_based_distanes):
        #index of assinged cluster
        assigned_cluster = preds[idx]
        #feature-wise distances of point to assigned cluster
        distances_to_assigned = e[:,assigned_cluster]
        
        assinged_cluster_list.append(assigned_cluster)
        fb_distance_to_assinged_cluster_list.append(distances_to_assigned)
        
        #find best alternative:
        
        temp_bad = []
        temp_idx = []
        
        #for every feature
        for i in range(num_features):
            
            
            # best alternative: 
            best_alternative_distance = min(e[:,i])
            x = e[:,i].tolist()
            idx_best_alternative = x.index(best_alternative_distance)
            
            
            #if the best alternative is the assigned cluster, we have to find the second best alternative
            if idx_best_alternative == assigned_cluster:
                
                del x[idx_best_alternative]
                best_alternative_distance = min(x)
                idx_best_alternative = x.index(best_alternative_distance)
                
            temp_bad.append(best_alternative_distance)
            temp_idx.append(idx_best_alternative)

        best_alterantive_list.append(temp_idx)
        fb_distance_to_best_alternative_list.append(temp_bad)     
            
    return np.array(assinged_cluster_list), np.array(fb_distance_to_assinged_cluster_list), np.array(best_alterantive_list), np.array(fb_distance_to_best_alternative_list)

In [20]:
ac ,fb_ac ,ba, fb_ba = best_second_calc(A, preds)

## Relevance of feature j for point i:

$$R_{ji} := R_j(x_{ij},c_{kj},c_{k'_{ij}}) := \frac{d_j(x_{ij},c_{k'_{ij}}) - d_j(x_{ij},c_{kj})}{d_j(x_{ij},c_{k'_{ij}}) + d_j(x_{ij},c_{kj})}$$

$d_j(x_{ij},c_{k'_{ij}}$ is the distance to the best alternative.

$d_j(x_{ij},c_{kj})$ is the distance to the associated cluster.

In [21]:
fb_ba[0]

array([0.8016129 , 0.42631579, 2.99354839])

In [22]:
fb_ac[0]

array([0.7516129 , 0.072     , 0.42631579])

In [23]:
ac[0]

1

In [24]:
ba[0]

array([0, 1, 0])

In [25]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [26]:
centers

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [27]:
preds[0]

1

In [28]:
y[0]

0

In [29]:
# broadcasted: for every i, for every j
R = (fb_ba - fb_ac) / (fb_ba + fb_ac)

In [30]:
R

array([[ 0.03219107,  0.71102662,  0.75068262],
       [ 0.5984556 , -0.70625262,  0.95195395],
       [ 0.45365854, -0.28698752,  0.92153968],
       [ 0.57463415, -0.85145573,  0.98197465],
       [ 0.02851886,  0.50738619,  0.7009454 ],
       [-0.39317073,  0.27290417,  0.53048428],
       [ 0.33278282,  0.8419489 ,  0.80341618],
       [ 0.16095535,  0.8419489 ,  0.79731084],
       [ 0.81658537, -0.55382571,  0.89032431],
       [ 0.48033373, -0.85145573,  0.98197465],
       [-0.30965594,  0.39442231,  0.64412502],
       [ 0.25666973,  0.8419489 ,  0.79081411],
       [ 0.62812872, -0.70625262,  0.95195395],
       [ 0.72845953, -0.70625262,  0.95623456],
       [-0.84982122,  0.23647604,  0.55031732],
       [-0.7824195 ,  0.15416323,  0.37139409],
       [-0.39317073,  0.27290417,  0.5783957 ],
       [ 0.03219107,  0.71102662,  0.75068262],
       [-0.67824968,  0.32259919,  0.57523706],
       [-0.13489991,  0.32259919,  0.5987055 ],
       [-0.13006993,  0.8419489 ,  0.783

In [31]:
#df = pd.DataFrame(R)
#df.rename({0:"R1", 1: "R2", 2: "R3", 3: "R4"}, axis=1, inplace = True)

In [32]:
#df.head()

In [33]:
#df["associated clusters"] = preds

In [34]:
#df["y"] = y

In [35]:
#df_X = pd.DataFrame(X)
#df.rename({0:"X1", 1: "X2", 2: "X3", 3: "X4"}, axis=1, inplace = True)

In [36]:
#df = pd.concat([df, df_X], axis=1)

In [37]:
#df