## Explainable k-Medoids

In [1]:
import matplotlib.pyplot as plt
from sklearn import datasets
import mpl_toolkits.mplot3d 
from sklearn.cluster import KMeans
from sklearn import metrics
import numpy as np
import pandas as pd

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [3]:
kmeans = KMeans(n_clusters=3, random_state=3).fit(X)

In [4]:
kmeans.inertia_

78.851441426146

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
preds = kmeans.predict(X)
print(preds)
print(preds.shape)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]
(150,)


### !! darf ich nicht so machen, da sonst fehler bei cluster zuordnung!

#prediction is "false" but only because the "label" is not correct, the class itself is correctly predicted. Maybe this needs to be solved later on differently.

lst = []

for i in preds:
    if i == 1: 
        lst.append(0)
    elif i == 0:
        lst.append(1)
    else:
        lst.append(i)
        
preds = np.array(lst)

In [7]:
preds

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)

In [8]:
metrics.accuracy_score(y,preds)

0.24

In [9]:
centers = kmeans.cluster_centers_
print(centers)
print(centers.shape)

[[5.9016129  2.7483871  4.39354839 1.43387097]
 [5.006      3.428      1.462      0.246     ]
 [6.85       3.07368421 5.74210526 2.07105263]]
(3, 4)


In [10]:
# one set of clusters for every obs - Idk. how to broadcast this to work with the later distance function
centers_lst = []

for i in preds:
    centers_lst.append(np.array(centers))
    
c = np.array(centers_lst)

In [11]:
c = np.array(centers_lst)

In [12]:
#Check obs
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [13]:
#check cluster
c[0]

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [14]:
#check point-wise Manhatten distance
abs(c[0] - X[0])

array([[0.8016129 , 0.7516129 , 2.99354839, 1.23387097],
       [0.094     , 0.072     , 0.062     , 0.046     ],
       [1.75      , 0.42631579, 4.34210526, 1.87105263]])

In [15]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [16]:
c

array([[[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]],

       [[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]],

       [[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]],

       ...,

       [[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]],

       [[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]],

       [[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.24

In [17]:
#check point-wise euclidean distance
(c[0] - X[0])**2

array([[6.42583247e-01, 5.64921956e-01, 8.96133195e+00, 1.52243757e+00],
       [8.83600000e-03, 5.18400000e-03, 3.84400000e-03, 2.11600000e-03],
       [3.06250000e+00, 1.81745152e-01, 1.88538781e+01, 3.50083795e+00]])

In [18]:
# to run with code above, I hashed the center_lst part
def calc_feature_wise_distance_matrix(distance_metric, points, cluster_centers):
    
    #centers_lst = []

    #for i in points:
    #    centers_lst.append(np.array(centers))
    
    c = np.array(centers_lst)

    # calculate the distance of every feature value of ever obs to every feature value in every cluster.
    
    feature_wise_distance_matrix = []
    
    if distance_metric == "manhattan":
        for i,e in enumerate(X):
            feature_wise_distance_matrix.append(abs(c[i] - e))
        
    
    if distance_metric == "euclidean":
        for i,e in enumerate(X):
            feature_wise_distance_matrix.append((c[i] - e)**2)
    
    return np.array(feature_wise_distance_matrix)

In [19]:
A =calc_feature_wise_distance_matrix("manhattan", X, c)

In [20]:
A[0]

array([[0.8016129 , 0.7516129 , 2.99354839, 1.23387097],
       [0.094     , 0.072     , 0.062     , 0.046     ],
       [1.75      , 0.42631579, 4.34210526, 1.87105263]])

In [21]:
A[0][:,1]

array([0.7516129 , 0.072     , 0.42631579])

In [22]:
centers

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [23]:
# Falsch!
def best_second_calc(feature_based_distances, preds):
    
    num_features = feature_based_distances.shape[2]
    
    assinged_cluster_list = []
    fb_distance_to_assinged_cluster_list = []
    
    best_alterantive_list = []
    fb_distance_to_best_alternative_list = []
    
    #for every obs:
    for idx, e in enumerate(feature_based_distances):
        #index of assinged cluster
        assigned_cluster = preds[idx]
        #feature-wise distances of point to assigned cluster
        distances_to_assigned = e[assigned_cluster]
        
        assinged_cluster_list.append(assigned_cluster)
        fb_distance_to_assinged_cluster_list.append(distances_to_assigned)
        
        #find best alternative:
        
        temp_bad = []
        temp_idx = []
        
        #for every feature
        for i in range(num_features):
            
            
            # best alternative: 
            best_alternative_distance = min(e[:,i])
            x = e[:,i].tolist()
            idx_best_alternative = x.index(best_alternative_distance)
            
            
            #if the best alternative is the assigned cluster, we have to find the second best alternative
            if idx_best_alternative == assigned_cluster:
                
                del x[idx_best_alternative]
                best_alternative_distance = min(x)
                idx_best_alternative = x.index(best_alternative_distance)
                
            temp_bad.append(best_alternative_distance)
            temp_idx.append(idx_best_alternative)

        best_alterantive_list.append(temp_idx)
        fb_distance_to_best_alternative_list.append(temp_bad)     
            
    return np.array(assinged_cluster_list), np.array(fb_distance_to_assinged_cluster_list), np.array(best_alterantive_list), np.array(fb_distance_to_best_alternative_list)

In [24]:
ac ,fb_ac ,ba, fb_ba = best_second_calc(A, preds)

## Relevance of feature j for point i:

$$R_{ji} := R_j(x_{ij},c_{kj},c_{k'_{ij}}) := \frac{d_j(x_{ij},c_{k'_{ij}}) - d_j(x_{ij},c_{kj})}{d_j(x_{ij},c_{k'_{ij}}) + d_j(x_{ij},c_{kj})}$$

$d_j(x_{ij},c_{k'_{ij}}$ is the distance to the best alternative.

$d_j(x_{ij},c_{kj})$ is the distance to the associated cluster.

In [25]:
fb_ba[0]

array([0.8016129 , 0.42631579, 2.99354839, 1.23387097])

In [26]:
fb_ac[0]

array([0.094, 0.072, 0.062, 0.046])

In [27]:
ac[0]

1

In [28]:
ba[0]

array([0, 1, 0, 0])

In [29]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [30]:
centers

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [31]:
preds[0]

1

In [32]:
y[0]

0

In [33]:
# broadcasted: for every i, for every j
R = (fb_ba - fb_ac) / (fb_ba + fb_ac)

In [34]:
R

array([[ 0.79008788,  0.71102662,  0.95941809,  0.92811775],
       [ 0.80859739, -0.70625262,  0.95941809,  0.92811775],
       [ 0.59406025, -0.28698752,  0.9004776 ,  0.92811775],
       [ 0.52448239, -0.85145573,  0.97407513,  0.92811775],
       [ 0.9867785 ,  0.50738619,  0.95941809,  0.92811775],
       [ 0.1201556 ,  0.27290417,  0.83762847,  0.74071258],
       [ 0.52448239,  0.8419489 ,  0.95941809,  0.90908103],
       [ 0.9867785 ,  0.8419489 ,  0.97407513,  0.92811775],
       [ 0.42494184, -0.55382571,  0.95941809,  0.92811775],
       [ 0.80859739, -0.85145573,  0.97407513,  0.8026855 ],
       [ 0.1201556 ,  0.39442231,  0.97407513,  0.92811775],
       [ 0.68492204,  0.8419489 ,  0.9058518 ,  0.92811775],
       [ 0.68492204, -0.70625262,  0.95941809,  0.8026855 ],
       [ 0.38811228, -0.70625262,  0.8019449 ,  0.8026855 ],
       [-0.77308745,  0.23647604,  0.84835981,  0.92811775],
       [-0.54977669,  0.15416323,  0.97407513,  0.74071258],
       [ 0.1201556 ,  0.

In [35]:
np.sum(R[:,0]) / len(R)

0.36975277918798033

In [36]:
np.sum(R[:,1]) / len(R)

0.13387253867696042

In [37]:
np.sum(R[:,2]) / len(R)

0.6688310755220815

In [38]:
np.sum(R[:,3]) / len(R)

0.5876523318789212

## Example Random Noise

In [39]:
def calc_feature_wise_distance_matrix(distance_metric, points, cluster_centers):
    
    centers_lst = []

    for i in points:
        centers_lst.append(np.array(centers))
    
    c = np.array(centers_lst)

    # calculate the distance of every feature value of ever obs to every feature value in every cluster.
    
    feature_wise_distance_matrix = []
    
    if distance_metric == "manhattan":
        for i,e in enumerate(X):
            feature_wise_distance_matrix.append(abs(c[i] - e))
        
    
    if distance_metric == "euclidean":
        for i,e in enumerate(X):
            feature_wise_distance_matrix.append((c[i] - e)**2)
    
    return np.array(feature_wise_distance_matrix)

In [40]:
df_X = pd.DataFrame(X)
df_X.rename({0:"X1", 1: "X2", 2: "X3", 3: "X4"}, axis=1, inplace = True)

In [41]:
X_5 = np.random.rand(150)
X_6 = np.random.rand(150)

In [42]:
df_X["X_5"] = X_5
df_X["X6"] = X_6

In [43]:
X = df_X.values
kmeans = KMeans(n_clusters=3, random_state=3).fit(X)

In [44]:
df_X

X1   X2   X3   X4       X_5        X6
0    5.1  3.5  1.4  0.2  0.941064  0.602081
1    4.9  3.0  1.4  0.2  0.188541  0.667386
2    4.7  3.2  1.3  0.2  0.005487  0.399049
3    4.6  3.1  1.5  0.2  0.603894  0.601577
4    5.0  3.6  1.4  0.2  0.967841  0.124909
..   ...  ...  ...  ...       ...       ...
145  6.7  3.0  5.2  2.3  0.955932  0.687757
146  6.3  2.5  5.0  1.9  0.143621  0.064506
147  6.5  3.0  5.2  2.0  0.205017  0.097586
148  6.2  3.4  5.4  2.3  0.327747  0.058750
149  5.9  3.0  5.1  1.8  0.202051  0.273138

[150 rows x 6 columns]

In [45]:
kmeans.inertia_

104.42178472506824

In [46]:
### !! darf ich nicht so machen, da sonst fehler bei cluster zuordnung!

#prediction is "false" but only because the "label" is not correct, the class itself is correctly predicted. Maybe this needs to be solved later on differently.
preds = kmeans.predict(X)

In [47]:
centers

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [48]:
centers = kmeans.cluster_centers_
print(centers)
print(centers.shape)

[[5.9016129  2.7483871  4.39354839 1.43387097 0.45383801 0.43467122]
 [5.006      3.428      1.462      0.246      0.5570346  0.46361045]
 [6.85       3.07368421 5.74210526 2.07105263 0.50011584 0.50431283]]
(3, 6)


In [58]:
A = calc_feature_wise_distance_matrix(distance_metric = "euclidean", points = X, cluster_centers=centers)

In [59]:
ac ,fb_ac ,ba, fb_ba = best_second_calc(A, preds)

In [60]:
# broadcasted: for every i, for every j
R = (fb_ba - fb_ac) / (fb_ba + fb_ac)

In [62]:
for i in range(6):
    print("R " + str(i), np.sum(R[:,i]) / len(R))

R 0 0.5007681159557349
R 1 0.19708184521500882
R 2 0.8163240638163629
R 3 0.7231487929167221
R 4 -0.07636595113663469
R 5 -0.15712834892303415
