## Gradient Explainer

In [48]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [62]:
import matplotlib.pyplot as plt
from sklearn import datasets
import mpl_toolkits.mplot3d 
from sklearn.cluster import KMeans
from sklearn import metrics
import numpy as np
import pandas as pd
from cxplain.xkm import Xkm
from cxplain.gradient import GradientExplainer  
from cxplain.metrics import EuclideanMetric, Metric, ManhattenMetric

In [63]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [51]:
kmeans = KMeans(n_clusters=3, random_state=3).fit(X)
cluster_centers = kmeans.cluster_centers_

In [52]:
cluster_centers

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [53]:
predictions = kmeans.predict(X)
predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [54]:
np.take(cluster_centers, predictions, axis=0)

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.006     , 3.428     ,

In [77]:
explainer = GradientExplainer(X, cluster_centers, predictions, ManhattenMetric, enable_abs_calculation=False)

In [78]:
exp = explainer.fit_explain()

In [79]:
exp.global_relevance

R1   -0.106667
R2   -0.013333
R3    0.053333
R4   -0.133333
dtype: float64